# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eee5d9c506c90392e873625c1fd7d4be4bfef6465f33f8ff614de23adbd7e44cddaf748c1e372b813b44f05f1c4a70259ed446e8798ba9f14933eb14342b923

test:
  secret_key_base: d9aecbd9ff028c7c36d86305981736b87c0c7e6c700e9bfda74eada2d5d8d1b5e6d7e1d357bb10a5f65c491a3542bf42e04794268c0642fd961bea28437389aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
